services:
  base-md:
    image: local/base-md
    build: docker/images/Base
  inkscape-md:
    image: local/inkscape-md
    build: docker/images/Inkscape
    depends_on:
      - base-md
    privileged: true
    container_name: inkscape-md
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/home/developer