services:
  base-md:
    image: local/base-md
    build: docker/images/Base
  inkscape-md:
    image: local/inkscape-md
    build: docker/images/Inkscape
    depends_on:
      - base-md
    privileged: true
    container_name: inkscape-md
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/home/developer
  gimp-md:
    image: local/gimp-md
    build: docker/images/Gimp
    depends_on:
      - base-md
    privileged: true
    container_name: gimp-md
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/home/developer
  openshot-md:
    image: local/openshot-md
    build: docker/images/Openshot
    depends_on:
      - base-md
    privileged: true
    container_name: openshot-md
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/home/developer
      - /dev/snd:/dev/snd
  nautilus-md:
    image: local/nautilus-md
    build: docker/images/Nautilus
    depends_on:
      - base-md
    privileged: true
    container_name: nautilus-md
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/home/developer
      - /dev/snd:/dev/snd
